### PR TITLE
Fix non tar static report serving

### LINKED ISSUE #117: Locust Report - HTTP 404
I was able to run the locust test successfully using Kangal. But when I query the report API, I am getting `404 page not found`. 

```
curl http://127.0.0.1:8081/load-test/loadtest-terrific-chinchilla/report/
```

Error:
```
404 page not found
```

### PR DESCRIPTION
**Pull request by diegomarangoni**
closes #117

Non-tar static files were unable to be served because they didn't have a dedicated condition for those kinds of files.
This PR adds a condition to handle non-tar files.

### CODE REVIEW

File: pkg/report/handler.go [hunk 1]
```diff
@@ -58,8 +58,21 @@ func ShowHandler() func(w http.ResponseWriter, r *http.Request) {
 			http.Error(w, err.Error(), http.StatusInternalServerError)
 			return
 		}
+
 		objStat, err := obj.Stat()
-		if nil == err && "application/x-tar" == objStat.ContentType {
+		// not found error can be a directory
+		if objErr, _ := err.(minio.ErrorResponse); http.StatusNotFound == objErr.StatusCode {
```
Comment (iammuho) [inline pkg/report/handler.go:64]: Why we are not returning the error here although it couldn't be found but still serving the file? Serving won't break because the file doesn't exist?

Comment (diegomarangoni) [reply pkg/report/handler.go:64]: >Why we are not returning the error here although it couldn't be found but still serving the file? Serving won't break because the file doesn't exist?

Not really, `http.FileServer(fs)` will look for `index.html` inside the directory (if is actually a directory) and proper handler in case not find anything

>Regarding to your comment, shouldn't we check if request is a directory ?

There is no way to check if is a directory or not, actually, S3 does not have directory concept at all.

**Review by iammuho — APPROVED** [review]

**Review by vgarvardt — APPROVED** [review]
